# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/phayes/permbits
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: gotestsum --junitfile /tmp/test-results -- -coverprofile=cover.out
      - run:
          name: Send coverage reports to Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter after-build cover.out --coverage-input-type=gocov --exit-code $?
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
